#!/usr/bin/env php

<?php
/**
 * @package     Console
 *
 * @subpackage  entrypoint
 *
 * @category    Console
 *
 * @since       2022.11.10
 *
 */

use console\Console;
use console\ConsoleKernel;

// Autoload global dependencies and allow for auto-loading local dependencies via use
require_once dirname(dirname(dirname(__DIR__))) . DIRECTORY_SEPARATOR . 'autoload.php';

// Require the app.php file to bootstrap the application.
$app = require_once dirname(dirname(__DIR__)) . DIRECTORY_SEPARATOR . 'core' . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'app.php';

// Resolve the console kernel instance.
$kernel = $app->resolve(ConsoleKernel::class);

// Boot up the application.
$kernel->bootstrap();

//Run the console application.
return $app->resolve(Console::class);
